export const PRODUCTS = [
    {
        id: 1,
        category: 1,
        name: 'Sandalia 1',
        description: '',
        color: '',
        price: 6000,
        image:require("../../assets/images/outlet.jpg"),
    },
    {
        id: 2,
        category: 1,
        name: 'Sueco 1',
        description: '',
        color: '',
        price: 7000,
        image:require("../../assets/images/outlet.jpg"),
    },
    {
        id: 3,
        category: 1,
        name: 'Sueco 2',
        description: '',
        color: '',
        price: 5000,
        image:require("../../assets/images/outlet.jpg"),
    },
    {
        id: 10,
        category: 2,
        name: 'Bota',
        description: '',
        color: '',
        price: 9000,
        image:require("../../assets/images/zapatos.jpg"),
    },
    {
        id: 11,
        category: 2,
        name: 'Borcego',
        description: '',
        color: '',
        price: 10000,
        image:require("../../assets/images/zapatos.jpg"),
    },
    {
        id: 20,
        category: 3,
        name: 'Cinto',
        description: '',
        color: '',
        price: 3000,
        image:require("../../assets/images/accesorios.jpg"),
    },
    {
        id: 21,
        category: 3,
        name: 'Billetera',
        description: '',
        color: '',
        price: 4000,
        image:require("../../assets/images/accesorios.jpg"),
    },
    {
        id: 22,
        category: 3,
        name: 'Billetera 2',
        description: '',
        color: '',
        price: 3999,
        image:require("../../assets/images/accesorios.jpg"),
    },
    {
        id: 30,
        category: 4,
        name: 'Cartera',
        description: '',
        color: '',
        price: 9000,
        image:require("../../assets/images/carteras.jpg"),
    },
    {
        id: 31,
        category: 4,
        name: 'Mochila 1',
        description: '',
        color: '',
        price: 7000,
        image:require("../../assets/images/carteras.jpg"),
    },
    {
        id: 32,
        category: 4,
        name: 'Mochila 2',
        description: '',
        color: '',
        price: 12000,
        image:require("../../assets/images/carteras.jpg"),
    },
]